name = "worker01"
main = "src/index.ts"
compatibility_date = "2025-08-30"

[[d1_databases]]
binding = "DB"                   # 代码里用 env.DB 访问
database_name = "test01"
database_id = "72586668-8ad1-43aa-b679-0af3f4646bd2"
migrations_dir = "drizzle" 
